# Use root/example as user/password credentials
version: '3.1'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      MSSQL_SA_PASSWORD: Admin123!@
      ACCEPT_EULA: true
    ports:
      - "1433:1433"
    volumes:
      - ./mongo:\\wsl$\docker-desktop-data\data\docker\volumes\mssql_data